server:
  port : 8080
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:D:/data/user-db
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd