server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: neuro
    password: userdb
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd

email:
  service:
    url: "http://localhost:8081/api/sendEmail"